// @desc    Accepts an image and returns a mock AI analysis
exports.analyzeLabel = (req, res) => {
  // Check if a file was uploaded by multer
  if (!req.file) {
    return res.status(400).json({ msg: 'No image file uploaded.' });
  }

  // --- MOCK AI RESPONSE ---
  const mockAIResponse = {
    name: 'Mock AI Wine',
    year: 2023,
    winery: 'Château de Mock',
    region: 'Faketown, France',
    grapeVariety: 'Cabernet Mockignon',
    aroma: ['blackberry', 'cedar', 'mock-spice'],
    taste: ['full-bodied', 'dry', 'hints of mockolate'],
    foodPairing: ['grilled steak', 'roast lamb', 'hard cheeses'],
    alcoholPercentage: 14.5,
    description: 'A beautifully mocked wine with a complex character, generated by a placeholder AI.',
    price: 50,
    oakAging: {
      oakType: 'French Mock',
      durationMonths: 18
    }
  };

  // Simulate a delay as if an AI was processing the image
  setTimeout(() => {
      res.json(mockAIResponse);
  }, 1500);
};
